[package]
name = "server"
version.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
net.workspace = true
tokio.workspace = true
env_logger.workspace = true
log.workspace = true
conf.workspace = true
clap = { version = "4.0", features = ["derive"] }
raft = { path = "../raft" }

[lints]
workspace = true
